### ISSUE TITLE
[redis] doesn't work with data defined by the redis-cli

### ISSUE THREAD

**Issue by ldez** [abronan/valkeyrie#34] opened 2020-01-21 14:03 UTC
Redis doesn't work with data defined by the redis-cli.

In fact, valkeyrie can only works with data created by valkeyrie.

A value created by the redis-cli:
```
foobar
```
A value created by valkeyrie:
```json
{"Key":"traefik/http/routers/Router1/rule","Value":"Zm9vYmFy","LastIndex":318341026}
```

The problem is mainly related to the `defaultCodec`, but not limited to that. (ex: the `mget` function is also a problem)

The current implementation information:
- https://github.com/abronan/valkeyrie/commit/334bf33436baeb2759ee7cb8ab1a906939255192
- https://github.com/docker/libkv/pull/143
- https://github.com/docker/libkv/issues/116
- https://redis.io/commands#

**Comment by leshik** [comment] 2020-01-23 04:39
@ldez I can confirm it now works with your fix to valkeyrie.
There are some tests there that fail because of linter warnings that prevent it from being merged AFAIR.

**Closed** 2020-01-27 17:42 UTC
